version: "3.8"

services:
  cairo:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3308:3306"
    volumes:
      - db-data1:/var/lib/mysql
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql

  alex:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3309:3306"
    volumes:
      - db-data2:/var/lib/mysql
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql

  giza:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3310:3306"
    volumes:
      - db-data3:/var/lib/mysql
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql

volumes:
  db-data1: {}
  db-data2: {}
  db-data3: {}
